name: "reddneck-local"
services:
  postgres:
    image: postgres:15.8-alpine
    restart: unless-stopped
    ports:
      - "${LOCAL_PG_PORT}:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 10
